# Generated by Django 3.1.7 on 2021-04-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermat',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
