# Generated by Django 3.1.7 on 2021-04-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ordermat_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='obekti',
            name='base',
            field=models.BooleanField(default=False),
        ),
    ]
